### ISSUE TITLE
"Borrow" template from BiocStyle

### ISSUE THREAD

**Issue by yixuan** [Bioconductor/BiocStyle#10]
Hi All,

Thanks for the nice work! Recently I wrote a package called [prettydoc](https://github.com/yixuan/prettydoc) that provides some lightweight themes and templates for R Markdown. Dirk [reminded me](https://github.com/yixuan/prettydoc/issues/1) that `BiocStyle` also contains a nice template, so I wonder if I could include this theme in future versions of my package.

My consideration is that for non-BioC users, they tend to only install packages from CRAN, so it may be more convenient for them to obtain this template from a CRAN package. But before doing that I think it would be better to get a permission from you authors, although technically the Artistic license that `BiocStyle` uses should be compatible with Apache 2 under which `prettydoc` is licensed. Of course I will list all of you in the authors field and your work will be appropriately acknowledged.

How do you think of this? Thanks!

**Comment by aoles** [comment]
Hi Yixuan,

thank you for your work on [prettydoc](https://github.com/yixuan/prettydoc), and for considering the inclusion of *BiocStyle* in it. I'm not entirely sure, thought, that our template is a good fit for your package.

One of the reasons is that even though the original style was indeed lightweight, the new implementation (`BiocStyle::html_document2`) piggy-backs on `rmarkdown::html_document` in order to provide advanced functionality such as floating TOC, foldable code chunks, and other goodies. So currently it doesn't actually match your concept of a lightweight theme. I will need to look into stripping it down a bit. Another thing is that we have developed the style mostly for Bioconductor related work, and releasing it on CRAN to general audience would probably loosen this type of identity. Last but not least, the style does not only consist of a single template file and tex/css style definitions, but there is also a substantial amount of code behind it. So by the end of the day you would need to copy more or less the entire content of the package in order to get things to work, which I don't really see the point of. Especially considering the fact that BiocStyle is being actively developed, so you would need to make sure that your package is not lagging behind.

Installing from Bioconductor is relatively straightforward, so you can always refer to *BiocStyle* along with short installation instructions, if you wish to.

Cheers,
Andrzej

**Comment by yixuan** [comment]
I see. Then I would probably just refer to BiocStyle rather than including it. Thanks!
