### ISSUE TITLE
 no \@ref in html_document

### ISSUE THREAD

**Issue by rdiaz02** [Bioconductor/BiocStyle#12]
It seems `BiocStyle::html_document` does not allow using custom labels as `{#somelabel}` and referencing it with `\@ref(somelabel)`  (see, e.g., https://bookdown.org/yihui/bookdown/cross-references.html ).

Playing with the code, I think that the only things that would need to be added to `html_document` are copying the `post_processor` function from `html_document2` and adding `post_processor = post_porcessor` in the final call to `rmarkdown::output_format`. 

I tried it, and it seems to work. I can submit a pull request, but am I missing something here?

**Comment by aoles** [comment]
Dear Ramon,

thank you for your suggestion. Indeed, `html_document` has limited functionality compared to `html_document2`; in fact, the former function will soon be deprecated and superseded by the latter one. Regarding the necessary updates, you're mostly right in your findings. Note that in order to handle custom labels one would also need to add a post processor to `pdf_document`. These changes are evident in my commit https://github.com/Bioconductor/BiocStyle/commit/773e5e3220503684b7b3cba135a28263d1dd98ce enabling bookdown-style cross references in BiocStyle v.2 Rmd documents.

Because we will be moving away from `html_document` to `html_document2`, I don't plan updating the former one to support custom labels. Thank you for your understanding.

Andrzej

**Comment by rdiaz02** [comment]
Understood. Thanks for looking into it.
