### ISSUE TITLE
latex 2.0 style footnotes

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/BiocStyle#3]
The margin notes are very nice in most cases, but I stumbled on the following issues

- When the footnote is actually an URL, it displays really badly in the margin. Is there a way to force it to be a footnote?

![2016-06-25-054701_680x285_scrot](https://cloud.githubusercontent.com/assets/384198/16354760/6413544c-3a98-11e6-9f80-06f0230bddec.png)

- ~~Is there a dedicated way to specify the authors' affiliations and/or email address. I think the email in the margin below looks a bit weird~~

Found this in the `LatexStyle2` vignette.

- I have the case where the footnote appears at the bottom of the page and overflows on the page number

![2016-06-25-054628_363x287_scrot](https://cloud.githubusercontent.com/assets/384198/16354759/4ace6012-3a98-11e6-8b08-0ff0b23e2a47.png)

**Comment by aoles** [comment]
Hi Laurent,
thank you for trying the new style and for reporting your issues with it!

The footnotes are currently implemented using the *[footmisc](https://www.ctan.org/pkg/footmisc)* LaTeX package. As you have noticed, apparently this approach is not robust enough and may lead to vertical overflows. I will need to investigate this further and look into possible alternatives.

Re typesetting URL's on the margin: BiocStyle does not offer overriding the placement of footnotes. If you are not happy with the results maybe you could either put it inline, or as a citation, i.e. have `\cite{myurl}` and a corresponding bibliography entry:

```
@misc{myurl,
  url = {http://www.example.com},
}
```

**Comment by aoles** [comment]
I did some research and found the following. Footnotes on the side are typeset as margin notes with `\marginpar`. The problem with this approach is that even though the notes are stacked one after the other so that they don't overlap, there is no mechanism for preventing them overflowing the bottom margin. This shortcoming is addressed by the LaTeX package *[marginfix](https://www.ctan.org/pkg/marginfix)*, see also the [article at TUGboat](https://www.tug.org/TUGboat/tb31-2/tb98hicks.pdf). It does a decent job, however, it is not ideal. In particular, it has some problems with accurate positioning of the side-notes: because the position of the notes is calculated before the glue in the main column is stretched (or shrunk), any stretch or shrink causes misalignment. Apart from this, when the package is loaded, the document seems to render with fixed page height similar to `\flushbottom`, as opposed to the default `\raggedbottom`. This is undesired as it tends to stretch the glue, which only makes things worse. I'm not sure where this comes from, but my guess is that this is probably an artifact of the package enforcing the margin height.

Because of the issues described above, I won't be enabling `marginfix` in BiocStyle, but you are welcome to load it manually by adding to your document header

```
\usepackage{marginfix}
```

**Comment by lgatto** [comment]
Thanks for looking into this. I would prefer to limit as much as possible relying on additional dependencies and let BiocStyle do it's thing. I am still exploring the new style, so I'll see how it goes.

**Comment by aoles** [comment]
Hi Laurent,
I had a second look at this and realized that I was using an outdated version of *marginfix* (0.9). The issues which I was initially concerned about have been resolved in the current release. Therefore, I've enabled *marginfix* in BiocStyle >= 2.1.13.

There is a caveat, though. It turns out that using *marginfix* may lead to some "color leakage", see my bug report at https://github.com/shicks/marginfix/issues/13. (This is similar to the issue already reported by you in https://github.com/Bioconductor/BiocStyle/issues/5, but funny enough, once *marginfix* is enabled the original problem goes away.) This can be observed, for example, in margin notes on pages on which there is a code chunk continuing from the previous page. Then the footnote gets typeset with the dark shade of gray which is the default foreground color in code chunks. I will look into possible solutions to this.

**Comment by aoles** [comment]
I'm happy to inform that I've managed to fix the remaining issue of margin notes being typeset with the wrong color. This required patching the internal LaTeX macro `\@savemarbox` which saves the box containing the `\marginpar` note, see https://github.com/Bioconductor/BiocStyle/commit/7e27133.

Don't hesitate to contact me in case there are any remaining issues with the formatting or positioning of footnotes.

Cheers,
Andrzej
