### ISSUE TITLE
BiocStyle repo should not be a Bioc-mirror fork

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocStyle#33]
There should be no forks coming out of `Bioconductor-mirror`. 
The mirror is deprecated.

Please update the BiocStyle repository in the git server if there are any differences
and use the git server repository version to create a new repository under
the Bioconductor account. 

Thanks!

Regards,
Marcel

**Comment by aoles** [comment]
Thank you Marcel. This repo is already in sync with the Bioconductor canonical git repo. I would prefer not to delete it because there is certain value in the issues (both open and closed ones) associated with this repo which we would loose otherwise. I believe that if any repo should be removed than it should be the Bioconductor-mirror one. Personally I don't really see the point of keeping a deprecated mirror alive which was read only anyway, so there isn't any added value which would get lost by deleting it.

**Comment by LiNk-NY** [comment]
Hi Andrzej, @aoles 
It's not about it being in sync. It's about the optics. 
There is increased confusion when users see that these repos are forked from the Bioconductor-mirror and they will think that it is okay to do so.
Thanks,
Marcel

**Comment by aoles** [comment]
Thanks! So, why is Bioconductor-mirror still alive in first place? I don't like the " forked from Bioconductor-mirror/BiocStyle" either, but I believe this is a transient issue anyway, and I think that loosing all the GitHub activity history associated with this repo would be even worse.
