### ISSUE TITLE
Documentation for, export status of html_fragment

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocStyle#38]
What's the official status of `html_fragment` in the [test workflow](https://www.bioconductor.org/help/workflows/testproj/testfile/)? Should I switch _simpleSingleCell_ to use it, or is there a reason why it is not exported?

**Comment by aoles** [comment]
Hi Aaron,
the reason why `html_fragment` is not exported is that it is not meant to be called by end users. Its output is not a valid self-contained HTML document but code meant for inclusion into the Bioconductor website. This format function is called by the workflow builders and overrides any user-specified format. Right now we are still in a test phase of this new engine. In order to enable it for your `simpleSingleCell` worfklow add an empty `.html_output` file in your vignette dir.

As a workflow developer you would normally specify in the vignette either `BiocStyle::html_document` or `BiocStyle::pdf_document`. If you intend to publish your workflow on F1000Research you can also use `BiocWorkflowTools::f1000_article`.

**Comment by LTLA** [comment]
Thanks Andrezj. To clarify; does this mean I replace `html_document` with `html_fragment` in my Rmarkdown file, _and_ add an empty `.html_output` in the `vignettes` directory?

**Comment by aoles** [comment]
As I already pointed out, you are not supposed to use BiocStyle's unexported functions. Adding just `.html_output` in the `vignettes` dir will do the job.

**Comment by LTLA** [comment]
Whoops, I was thinking of "end user" as actual users, not package developers.
