### ISSUE TITLE
Footnotes not being resolved in BiocStyle::html_document output format

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/BiocStyle#48]
Footnotes, at least those defined using the [`inline_notes` **pandoc** extension](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html#footnotes), don't appear to be properly resolved when using `BiocStyle::html_document` output format. They do appear to work when using `html_document` output format, so this suggests to me it's something going wonky with **BiocStyle** rather than **rmarkdown**.

An example is given in https://github.com/Bioconductor/BiocStyle/blob/master/vignettes/AuthoringRmdVignettes.Rmd#margin-notes, which doesn't appear to be rendered in https://bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html#10_margin_notes.

**Comment by aoles** [comment]
Thanks Peter for reporting this, I was able to reproduce the described problem.

For the record, footnotes used to work in [BioC 3.6](http://bioconductor.org/packages/3.6/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html#session_info); doesn't seem to directly related to rmarkdown or bookdown as I still get the same behavior with archived versions listed in `sessionInfo`. This might indicate some pandoc issue. Unfortunately, it doesn't seem possible to recover the version of pandoc which was used to render the vignette in BioC 3.6 because https://github.com/Bioconductor/BBS/issues/56 hasn't been implemented yet..

**Comment by PeteHaitch** [comment]
Thanks, @aoles. Can confirm this works locally, but I don't see the change reflected on the BioC website (specifically for, https://bioconductor.org/packages/devel/bioc/vignettes/SummarizedExperiment/inst/doc/Extensions.html). Any ideas?

**Comment by aoles** [comment]
That's because one needs to rebuild the affected package vignettes with the updated version of BiocStyle, both in release and devel. As the would happen only on package version bump, we will probably need to bump the version of all packages which use footnotes in their BiocStyle-enabled Rmd vignettes (CC @mtmorgan @vobencha @lshep).

**Comment by lshep** [comment]
I performed a version bump on the above list of packages -  They should all get updated on tomorrow's build.

**Comment by aoles** [comment]
Thanks Lori! Most of the vignettes rebuilt fine, however, for some reason **CAGEr**, **microbiome** and **RforProteomics** in both release and devel still don't display footnotes properly. Not sure why yet..

**Comment by aoles** [comment]
Thanks @PeteHaitch! The reason why footnotes in **SummarizedExperiment** are still broken is that the package failed to rebuild after the update (the vignette displayed on the website is for version 1.11.3 which is from two weeks ago, just before the fix in BiocStyle was introduced).

There are still, however, issues with **CAGEr** and **RforProteomics**. As described in my previous comment, the problem was due to multi-line footnotes, a separate issue from the original problem from the beginning of this thread. I believe this has been fixed too in the recent update to BiocStyle. @lshep, would you mind triggering a rebuild of theses two packages in both release and devel?

**microbiome** turned out to be a false positive. It's vignette doesn't use footnotes, the search just matched to a comment describing how to use them.

Cheers,
Andrzej

**Comment by PeteHaitch** [comment]
Woops, I misunderstood the issue. Thanks for clarifying!

**Comment by PeteHaitch** [comment]
Confirming this is now fixed in **SummarizedExperiment**. Thanks again!
