### ISSUE TITLE
BiocStyle is broken with the latest knitr version

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocStyle#78]
With **knitr** 1.30 released today, **BiocStyle** breaks with:

```r
rmarkdown::render("AuthoringRmdVignettes.Rmd")
## 
## 
## processing file: AuthoringRmdVignettes.Rmd
##   |.....                                                                 |   7%
##    inline R code fragments
## 
##   |..........                                                            |  14%
## label: macro (with options) 
## List of 1
##  $ echo: logi FALSE
## 
## Quitting from lines 183-187 (AuthoringRmdVignettes.Rmd) 
## Error in if (is.na(options$out.width.px)) options$out.width.px = options$fig.width *  : 
##   argument is of length zero
```

It seems that `out.width.px` and `out.height.px` no longer exist. Deleting the relevant lines in `knitr_options.R` seems sufficient to restore functionality.

**Comment by lshep** [comment]
I think there might need to be a larger evaluation of what has changed in knitr.  I have a package in the SPB that is failing on the following code chunk as well 
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**Comment by LTLA** [comment]
Really? With the PR in #79, the following compiles fine for me:

````
---
title: YAY
output:
  BiocStyle::html_document
---


```{r}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
print("YA")
```
````

**Comment by lshep** [comment]
Sorry -- didnt install after I built the new.

**Comment by grimbough** [comment]
@aoles  I think the patch in #79  should be sufficient to fix this.

The `out.width.px` option isn't gone per-se, but it doesn't exist until `fix_options()` has been called and [knitr v1.30](https://github.com/yihui/knitr/releases/tag/v1.30) moved `knitr::fix_options()` after the hooks.

Based on the existence of this comment https://github.com/Bioconductor/BiocStyle/blob/e3c52aa8b9016c50e869e7dc1af4cbeb6db7492d/R/knitr_options.R#L51
it seems like we can do away with the testing and recalculation of `options.width.px` and `options.height.px` since that comment no longer applies, and rely on `knitr` doing things correctly itself.

**Comment by aoles** [comment]
Thanks both to @LTLA and @grimbough for looking into the issue!

Indeed, the re-evaluation of `options$out.width.px` and `options$out.height.px` was necessary only because of the bug which has been eventually fixed in https://github.com/yihui/knitr/pull/1877 effectively rendering the corresponding code in BiocStyle obsolete.

**Comment by lshep** [comment]
Any chance of getting a fix in before 2:30 PM (14:30) EST today so that tomorrow's build reports could be back to normal?  We are seeing hundreds of packages affected in release and devel.

**Comment by grimbough** [comment]
Yes, I'll do the merge in the next hour.

**Comment by grimbough** [comment]
I didn't mean to close this quite yet!

**Comment by grimbough** [comment]
Patch has now been pushed to both release and devel branches.  Tested locally on a few of my packages and all looks ok, fingers crossed for tomorrow's build reports.

**Comment by MarcElosua** [comment]
Hi all,
I am trying to use BiocStyle to render an Rmarkdown document and I cannot seem to find where I am going wrong.
I am using R version 3.6.3 and the following package versions:

```
> packageVersion('rmarkdown')
[1] ‘2.5’
> packageVersion("knitr")
[1] ‘1.30’
> packageVersion("BiocStyle")
[1] ‘2.14.4’
---
title: YAY
output:
  BiocStyle::html_document
---


```{r}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(BiocStyle)
print("YA")
```
As a minimal example I am using the YAY example [above](https://github.com/Bioconductor/BiocStyle/issues/78#issuecomment-697702420) by LTLA. And I am still getting the error:
```
Quitting from lines 9-13 (yay.Rmd) 
Error in if (is.na(options$out.width.px)) options$out.width.px = options$fig.width *  : 
  argument is of length zero
Calls: <Anonymous> ... process_group.block -> call_block -> as.strict_list -> hook
Execution halted
```

Any help on how to fix this is greatly appreciated!

**Comment by LiNk-NY** [comment]
Hi @MarcElosua 

Make sure you are using the latest version of Bioconductor `3.12`.
This patch may also work with Bioconductor version `3.11`. 
That means you should have R version 4.0 or greater installed.

Best,
Marcel
