### ISSUE TITLE
`fig.small` figures are only displayed when the browser window is sufficiently narrow

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocStyle#83]
See https://stat.ethz.ch/pipermail/bioc-devel/2020-November/017483.html

**Comment by AIB-KQC** [comment]
could you show me the picture? Thank you.

**Comment by sudeepsahadevan** [comment]
Hi @AIB-KQC 
Here is one of the pictures that didn't render properly
![image_issue](https://user-images.githubusercontent.com/1842874/99769076-14946600-2b06-11eb-9ae0-c940d498869a.png)

**Comment by aoles** [comment]
Thanks @grimbough for looking into it!

The problem appears also in the BiocStyle vignette itself, both in release and devel. The small figures seem to be broken for a while now, as they don't show up in the [vignette on the 3.11 branch](https://www.bioconductor.org/packages/3.11/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html#6_Figures`) compiled on September 20 too.

**Comment by grimbough** [comment]
Yes, I think this is related to the changes on knitr that also caused #78 but this time it's a subtle difference rather than a breaking change. That's why we see it with the old version of BiocStyle, because it's still using the most recent knitr.

I think knitr now sets a `out.width` if one isn't specified, and this overrides or negates the "100%" BiocStyle tries to set.  Short term fix is probably to put `out.width="100%"` in the chunk options, and then I'll try to get a patch that restores the old behaviour.

**Comment by grimbough** [comment]
Hopefully this is now fixed in BiocStyle versions 2.18.1 and 2.19.1.  @sudeepsahadevan please let us know if it's still an issue.

**Comment by sudeepsahadevan** [comment]
Thank you @grimbough,

Now class "smallfigure" images are rendered properly.
